version: '3.7'
services:
  tjmt-publicador:
    image: tjmt/publicador:${IMAGE_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TimeZone: ${TIMEZONE}
        Language: ${LANGUAGE}
        Unicode: ${UNICODE}
        KUBECTL_VERSION: ${KUBECTL_VERSION} #https://github.com/kubernetes/kubernetes/releases
        KOMPOSE_VERSION: ${KOMPOSE_VERSION} #https://github.com/kubernetes/kompose/releases
        NUGET_VERSION: ${NUGET_VERSION} #https://www.nuget.org/downloads
        NODE_VERSION: ${NODE_VERSION} #https://nodejs.org/en/download/
